"""Format output files with safety banners and summaries."""

from __future__ import annotations

from sp_debug.transform import TransformStats


def debug_banner(parse_errors: list[str], stats: TransformStats) -> str:
    lines = [
        "-- ============================================================================",
        "-- DEBUG HARNESS — DO NOT RUN ON PRODUCTION",
        "-- Generated by sp-debug. DML replaced with SELECT previews; variable traces injected.",
        "-- ============================================================================",
        f"-- DML statements stubbed: {stats.dml_stubbed}",
        f"-- Trace lines added: {stats.traces_added}",
    ]
    if parse_errors:
        lines.append("-- PARSE WARNINGS (review manually):")
        for err in parse_errors:
            lines.append(f"--   {err}")
    for w in stats.warnings:
        lines.append(f"--   {w}")
    lines.append("-- ============================================================================")
    lines.append("")
    return "\n".join(lines) + "\n"
